name: GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release from tag ${{ github.ref_name }}.
            
            ## Changes
            - Update in supermarket inventory project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
